import Head from 'next/head'
import * as THREE from "three";
import { Canvas } from '@react-three/fiber'
import Scene from '@/components/Scene'

import { OrbitControls } from '@react-three/drei';

import InfoBar from '@/components/infoPane'

import React, { useState } from 'react'
import { Planet } from '../components/types';

export default function Home() {
     
  const [Info, setInfo] = useState<Planet | null>(null);

  let camera = new THREE.PerspectiveCamera (120, 1.5, 0.1, 10000);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-screen h-screen flex-row flex'>
        <InfoBar Info={Info}/>
        <div id="canvas-container" className="w-screen h-screen absolute flex-col justify-center items-center">
          <Canvas className='bg-black' >
         
            <Scene setInfo={setInfo} />
           
          </Canvas>
        </div>
        
      </main>
    </>
  )
}
